# Generated by Django 3.0 on 2021-11-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentospregao',
            name='declaracao_de_MEPP',
            field=models.FileField(blank=True, upload_to='documentos'),
        ),
    ]
