# Generated by Django 3.0 on 2021-11-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20211125_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentospregao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
