# Generated by Django 3.0 on 2021-11-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_auto_20211122_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentospregao',
            name='cpf',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='documentospregao',
            name='nome',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
