# Generated by Django 3.0 on 2021-11-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_auto_20211122_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentospregao',
            name='contrato_social',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
